name: Example test execution

env:
  DEFAULT_SUITE: 'smoke.xml'

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Run tests
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:

      - name: Step 1 - Checkout the code
        uses: actions/checkout@v2

      - name: Step 2 - Setup Java and Maven
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Step 3 - Install nodejs
        run: sudo apt install nodejs

      - name: Step 4 - Install test reporter
        run: sudo npm i test-results-reporter

      - name: Step 5 - Run tests
        run: mvn clean test -DsuiteXmlFile=src/test/resources/${{env.DEFAULT_SUITE }}