name: Example test execution

env:
  DEFAULT_SUITE: 'smoke.xml'

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Run tests
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:

      - name: Step 1 - Checkout the code
        uses: actions/checkout@v2

      - name: Step 2 - Setup Java and Maven
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Step 3 - Install nodejs
        uses: actions/setup-node@v2
        with:
          node-version: '12.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Step 4 - Run tests
        run: mvn clean test -DsuiteXmlFile=src/test/resources/${{env.DEFAULT_SUITE }}

      - name: Step 5 - Publish results
        if: ${{ always() }}
        run: npx test-results-reporter publish -c test-output/testng-results.xml
        env:
          SLACK_URL: ${{ secrets.SLACK_URL }}